title: 'Obyte — a ledger without middlemen'
default_lang: en
author:
  name: Obyte
taxonomies:
  - category
  - tag
metadata:
  description: 'A ledger without middlemen. Block-free, miner-free, DAG based.'
  og:description: 'A ledger without middlemen. Block-free, miner-free, DAG based.'
  og:type: 'website'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
