absolute_urls: false

home:
  alias: '/home'

pages:
  theme: obyte
  markdown:
    extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    method: none
  driver: auto
  prefix: 'g'

twig:
  cache: false
  debug: false
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true
  collections:
    jquery: https://code.jquery.com/jquery-3.6.0.min.js

errors:
  display: true
  log: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
gpm:
  releases: stable
  verify_peer: true
